"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](#FAFAFA)\
$os\
$username\
[](fg:#FAFAFA bg:#D4D4D4)\
$directory\
[](fg:#D4D4D4 bg:#A3A3A3)\
$git_branch\
$git_status\
[](fg:#A3A3A3 bg:#525252)\
$docker_context\
[ ](fg:#525252)\
"""

# -----------------------------
# OS
# -----------------------------
[os]
disabled = false
style = "bg:#FAFAFA fg:#0A0A0A"
format = '[ $symbol ]($style)'

[os.symbols]
Macos = ""
Ubuntu = ""
Windows = "󰍲"
Arch = ""
Fedora = ""
Debian = ""

# -----------------------------
# USERNAME
# -----------------------------
[username]
show_always = false
style_user = "bg:#FAFAFA fg:#0A0A0A"
style_root = "bg:#FAFAFA fg:#0A0A0A"
format = '[$user ]($style)'
disabled = false

# -----------------------------
# DIRECTORY
# -----------------------------
[directory]
style = "bg:#D4D4D4 fg:#111111"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_os_path_sep = true
home_symbol = "󰋜 ~"
truncation_symbol = "…/"

[directory.substitutions]
"Developer" = "󰲋 Developer"
"Projects" = "󱌣 Projects"
"Workspace" = "󱂬 Workspace"
"Code" = "󰨞 Code"
"Repos" = "󰳏 Repos"
"Documents" = "󱂷 Documents"
"Downloads" = "󰉍 Downloads"
"Music" = "󱍙 Music"
"Pictures" = "󰉏 Pictures"
"Desktop" = "󰟀 Desktop"
".config" = " .config"
".git" = "󰊢 .git"

# -----------------------------
# GIT
# -----------------------------
[git_branch]
symbol = ""
style = "bg:#A3A3A3 fg:#FAFAFA"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#A3A3A3"
format = '([$staged$modified$untracked$renamed$deleted$conflicted$ahead_behind]($style))'

staged = '[+${count} ](bold bright-green bg:#A3A3A3)'
modified = '[!${count} ](bold #FF9100 bg:#A3A3A3)'
untracked = '[?${count} ](bold bright-cyan bg:#A3A3A3)'
deleted = '[✘${count} ](bold #FF1744 bg:#A3A3A3)'
renamed = '[→ ](bold #00E5FF bg:#A3A3A3)'
conflicted = '[⚑ ](bold #FF1744 bg:#A3A3A3)'

ahead = '[⇡${count} ](bold bright-green bg:#A3A3A3)'
behind = '[⇣${count} ](bold #FF1744 bg:#A3A3A3)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count} ](bold #FFEA00 bg:#A3A3A3)'

# -----------------------------
# DOCKER
# -----------------------------
[docker_context]
symbol = ""
style = "bg:#525252 fg:#FAFAFA"
format = '[ $symbol $context ]($style)'
